language: python
python:
  - "3.13"

install:
  - pip install -r requirements.txt

script:
  - black --check .
  - flake8 .
  - coverage run --source='.' manage.py test
  - coveralls

branches:
  only:
    - master
