language: python
python:
  - "3.12"

install:
  - pip install -r requirements.txt

script:
  - black --check .
  - flake8 .
  - coverage run --source='.' manage.py test
  - coveralls

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: django_tutorial
  env: swe1-app-env
  bucket_name: elasticbeanstalk-us-east-1-981381909034
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY

branches:
  only:
    - master
