[project]
name = "django-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.9.0",
    "coverage>=7.10.7",
    "coveralls>=4.0.1",
    "django>=5.2.6",
    "flake8>=7.3.0",
]
